name: GitHub Container registry cleaning
description: Clean a GitHub Container registry by removing all unnecessary objects
inputs:
  # Container registry inputs.
  registry:
    description: The URL of the container registry
    default: ghcr.io
  user:
    description: The container registry user
    default: ${{ github.repository_owner }}
  password:
    description: The container registry user password or access token
  package:
    description: The name of the package to clean
    default: ${{ github.repository }}

  # Repository inputs.
  repository:
    description: Repository name with owner, for example, `pcasteran/ghcr-cleaning-action`
    default: ${{ github.repository }}
  pr-tag-regex:
    description: The regular expression used to match the pull request tags
    default: "^pr-(\\d+).*"

  # Misc inputs.
  dry-run:
    description: If true, compute everything but do no perform the deletion
    default: false
  debug:
    description: Enable the debug logs
    default: false

runs:
  using: docker
  image: Dockerfile
  args:
    - -registry
    - ${{ inputs.registry }}
    - -user
    - ${{ inputs.user }}
    - -password
    - ${{ inputs.password }}
    - -package
    - ${{ inputs.package }}
    - -repository
    - ${{ inputs.repository }}
    - -pr-tag-regex
    - ${{ inputs.pr-tag-regex }}
    - -dry-run
    - ${{ inputs.dry-run }}
    - -debug
    - ${{ inputs.debug }}
